package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"

	"github.com/kcrobinson-1/workstream-tracker/internal/models"
	"github.com/kcrobinson-1/workstream-tracker/internal/slugs"
)

var (
	errRootNotRegistered = errors.New("root not registered")
	errSlugConflict      = errors.New("slug conflict")
)

// registerWorkInstance handles POST /work-instances.
//
// Three flows. ExactSlug, when non-empty, selects the third and
// bypasses the other two:
//   - ParentPath nil, no ExactSlug: root case (new epic or
//     standalone task plan). Slug = request.RootSlug, validated for
//     kebab-case and root uniqueness.
//   - ParentPath non-nil, no ExactSlug: descendant case. Slug =
//     generated by appending the next available position number to
//     (RootSlug + ParentPath + type letter).
//   - ExactSlug non-empty: create-or-attach. Slug = ExactSlug
//     verbatim (validated for slug grammar only); creates the
//     slug's first work-instance if none exists, else attaches an
//     additional one. No root-conflict check.
//
// Across all three flows, an already-active work-instance for the
// resolved (slug, actor) pair collapses to the existing row.
func (s *Server) registerWorkInstance(w http.ResponseWriter, r *http.Request) {
	var req RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: %v", err)
		return
	}

	if req.Actor == "" {
		writeError(w, http.StatusBadRequest, "actor is required")
		return
	}

	ctx := r.Context()

	if req.ExactSlug != "" {
		if !slugs.IsWellFormed(req.ExactSlug) {
			writeError(w, http.StatusBadRequest, "exact_slug %q is not a well-formed slug (kebab-case root, optionally followed by mN/tN/pN segments)", req.ExactSlug)
			return
		}
	} else {
		if req.RootSlug == "" {
			writeError(w, http.StatusBadRequest, "root_slug is required")
			return
		}
		if !slugs.IsValidRoot(req.RootSlug) {
			writeError(w, http.StatusBadRequest, "root_slug must be kebab-case (lowercase letters, digits, hyphens between segments)")
			return
		}
		if !slugs.ValidNodeType(req.NodeType) {
			writeError(w, http.StatusBadRequest, "node_type must be one of: epic, milestone, task, phase")
			return
		}

		if req.ParentPath == nil {
			if req.NodeType != "epic" && req.NodeType != "task" {
				writeError(w, http.StatusBadRequest, "root case requires node_type epic or task")
				return
			}
		} else {
			if req.NodeType == "epic" {
				writeError(w, http.StatusBadRequest, "epics cannot be descendants")
				return
			}
		}
	}

	wid := uuid.NewString()
	eid := uuid.NewString()
	now := time.Now().UTC()

	id, slug, err := insertRegister(ctx, s.db, eid, wid, req, now)
	if err != nil {
		switch {
		case errors.Is(err, errSlugConflict):
			writeError(w, http.StatusConflict, "slug %q is already registered", req.RootSlug)
		case errors.Is(err, errRootNotRegistered):
			writeError(w, http.StatusBadRequest, "root %q has not been registered", req.RootSlug)
		default:
			slog.Error("insert register", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
		}
		return
	}

	writeJSON(w, http.StatusCreated, RegisterResponse{ID: id, Slug: slug})
}

// recordEvent handles POST /work-instances/{id}/events.
//
// Two event shapes:
//   - State empty → heartbeat: appends event, bumps last_updated_at.
//   - State "completed" or "abandoned" → state transition: appends
//     event, updates state and terminal_at.
func (s *Server) recordEvent(w http.ResponseWriter, r *http.Request) {
	wid := chi.URLParam(r, "id")
	if wid == "" {
		writeError(w, http.StatusBadRequest, "work-instance id is required")
		return
	}

	var req EventRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: %v", err)
		return
	}

	ctx := r.Context()

	exists, err := workInstanceExists(ctx, s.db, wid)
	if err != nil {
		slog.Error("check work-instance existence", "err", err)
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}
	if !exists {
		writeError(w, http.StatusNotFound, "work-instance %q not found", wid)
		return
	}

	eid := uuid.NewString()
	now := time.Now().UTC()

	switch req.State {
	case "":
		if err := insertHeartbeat(ctx, s.db, eid, wid, req.Metadata, now); err != nil {
			slog.Error("insert heartbeat", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
	case string(models.StateCompleted), string(models.StateAbandoned):
		payload, err := json.Marshal(map[string]string{"state": req.State})
		if err != nil {
			slog.Error("marshal state payload", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
		if err := insertStateTransition(ctx, s.db, eid, wid, req.State, payload, req.Metadata, now); err != nil {
			slog.Error("insert state transition", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
	default:
		writeError(w, http.StatusBadRequest, "state must be empty (heartbeat), %q, or %q", models.StateCompleted, models.StateAbandoned)
		return
	}

	writeJSON(w, http.StatusCreated, EventResponse{ID: eid})
}

// insertRegister resolves the slug for the request's flow and
// inserts the register event + initial work_instance row in one
// write transaction, returning the work-instance id and slug.
//
// db.Open configures SQLite transactions as BEGIN IMMEDIATE, so the
// slug resolution read, the (slug, actor, active) idempotency read,
// and the insert are serialized: two concurrent registrations for
// the same active (slug, actor) pair cannot both insert.
//
// Idempotency: if an active work-instance already exists for the
// resolved (slug, actor) pair, no new row and no new register event
// are written; the existing id and slug are returned. A terminal
// prior work-instance for the pair does not block a fresh
// registration (serial resume); a different actor on the same slug
// is independent (co-working).
func insertRegister(ctx context.Context, db *sql.DB, eid, wid string, req RegisterRequest, now time.Time) (string, string, error) {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return "", "", err
	}
	defer tx.Rollback()

	slug := req.RootSlug
	parentPath := ""
	if req.ExactSlug != "" {
		// Create-or-attach: honor the caller's slug verbatim. No
		// derivation, no descendant generation, no root-conflict
		// check. Grammar was validated by the handler.
		slug = req.ExactSlug
	} else if req.ParentPath != nil {
		parentPath = *req.ParentPath
		exists, err := rootExists(ctx, tx, req.RootSlug)
		if err != nil {
			return "", "", err
		}
		if !exists {
			return "", "", errRootNotRegistered
		}
		generated, err := generateDescendantSlug(ctx, tx, req.RootSlug, parentPath, req.NodeType)
		if err != nil {
			return "", "", err
		}
		slug = generated
	} else {
		exists, err := rootExists(ctx, tx, req.RootSlug)
		if err != nil {
			return "", "", err
		}
		if exists {
			return "", "", errSlugConflict
		}
	}

	// Idempotency on (slug, actor, state = active). Runs after the
	// bare root-conflict rejection above, so a duplicate bare
	// root-create still 409s; idempotency is observable on the
	// exact-slug flow and on serial resume.
	if existingID, found, err := activeWorkInstanceID(ctx, tx, slug, req.Actor); err != nil {
		return "", "", err
	} else if found {
		return existingID, slug, nil
	}

	payload, err := json.Marshal(map[string]string{
		"root_slug":   req.RootSlug,
		"parent_path": parentPath,
		"node_type":   req.NodeType,
		"actor":       req.Actor,
		"slug":        slug,
	})
	if err != nil {
		return "", "", err
	}

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		eid, wid, models.EventRegister, payload, nullableJSON(req.Metadata), now.UnixNano(),
	)
	if err != nil {
		return "", "", fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`INSERT INTO work_instances (id, slug, actor, state, created_at, last_updated_at, terminal_at)
		 VALUES (?, ?, ?, ?, ?, ?, NULL)`,
		wid, slug, req.Actor, models.StateActive, now.UnixNano(), now.UnixNano(),
	)
	if err != nil {
		if isUniqueConstraint(err) {
			return "", "", errSlugConflict
		}
		return "", "", fmt.Errorf("insert work_instance: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return "", "", err
	}
	return wid, slug, nil
}

// activeWorkInstanceID returns the id of an active work-instance for
// the exact (slug, actor) pair, if one exists. The idempotency key
// is (slug, actor, state = active): a terminal prior row for the
// pair does not match, so serial resume after pause is permitted; a
// different actor on the same slug does not match, so concurrent
// co-working is permitted.
func activeWorkInstanceID(ctx context.Context, db dbReader, slug, actor string) (string, bool, error) {
	var id string
	err := db.QueryRowContext(ctx,
		`SELECT id FROM work_instances
		 WHERE slug = ? AND actor = ? AND state = ?
		 LIMIT 1`,
		slug, actor, models.StateActive,
	).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return "", false, nil
	}
	if err != nil {
		return "", false, fmt.Errorf("check active work_instance: %w", err)
	}
	return id, true, nil
}

// insertHeartbeat appends a heartbeat event and bumps the
// work_instance's last_updated_at.
func insertHeartbeat(ctx context.Context, db *sql.DB, eid, wid string, metadata json.RawMessage, now time.Time) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, NULL, ?, ?)`,
		eid, wid, models.EventHeartbeat, nullableJSON(metadata), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`UPDATE work_instances SET last_updated_at = ? WHERE id = ?`,
		now.UnixNano(), wid,
	)
	if err != nil {
		return fmt.Errorf("update work_instance: %w", err)
	}

	return tx.Commit()
}

// insertStateTransition appends a state-transition event and
// updates the work_instance's state, last_updated_at, and
// terminal_at.
func insertStateTransition(ctx context.Context, db *sql.DB, eid, wid, state string, payload, metadata json.RawMessage, now time.Time) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		eid, wid, models.EventStateTransition, payload, nullableJSON(metadata), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`UPDATE work_instances SET state = ?, last_updated_at = ?, terminal_at = ? WHERE id = ?`,
		state, now.UnixNano(), now.UnixNano(), wid,
	)
	if err != nil {
		return fmt.Errorf("update work_instance: %w", err)
	}

	return tx.Commit()
}

// workInstanceExists reports whether a work-instance with the
// given ID is present.
func workInstanceExists(ctx context.Context, db *sql.DB, id string) (bool, error) {
	var exists bool
	err := db.QueryRowContext(ctx,
		`SELECT EXISTS(SELECT 1 FROM work_instances WHERE id = ?)`,
		id,
	).Scan(&exists)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return false, err
	}
	return exists, nil
}

func isUniqueConstraint(err error) bool {
	var sqliteErr *sqlite.Error
	if !errors.As(err, &sqliteErr) {
		return false
	}
	code := sqliteErr.Code()
	return code == sqlite3.SQLITE_CONSTRAINT_UNIQUE || code&0xff == sqlite3.SQLITE_CONSTRAINT
}

// nullableJSON returns nil if the raw message is empty, otherwise
// the raw message itself. Lets sql.Exec write NULL when the
// caller passed no metadata.
func nullableJSON(raw json.RawMessage) any {
	if len(raw) == 0 {
		return nil
	}
	return []byte(raw)
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, status int, format string, args ...any) {
	writeJSON(w, status, map[string]string{"error": fmt.Sprintf(format, args...)})
}
