package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"

	"github.com/kcrobinson-1/workstream-tracker/internal/models"
)

// registerWorkInstance handles POST /work-instances.
//
// Two flows determined by request.ParentPath:
//   - nil: root case (new epic or standalone task plan). Slug =
//     request.RootSlug, validated for kebab-case and uniqueness.
//   - non-nil: descendant case. Slug = generated by appending the
//     next available position number to (RootSlug + ParentPath +
//     type letter).
func (s *Server) registerWorkInstance(w http.ResponseWriter, r *http.Request) {
	var req RegisterRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: %v", err)
		return
	}

	if req.RootSlug == "" {
		writeError(w, http.StatusBadRequest, "root_slug is required")
		return
	}
	if !rootSlugPattern.MatchString(req.RootSlug) {
		writeError(w, http.StatusBadRequest, "root_slug must be kebab-case (lowercase letters, digits, hyphens between segments)")
		return
	}
	if !validNodeType(req.NodeType) {
		writeError(w, http.StatusBadRequest, "node_type must be one of: epic, milestone, task, phase")
		return
	}
	if req.Actor == "" {
		writeError(w, http.StatusBadRequest, "actor is required")
		return
	}

	ctx := r.Context()

	var slug string
	if req.ParentPath == nil {
		// Root case.
		if req.NodeType != "epic" && req.NodeType != "task" {
			writeError(w, http.StatusBadRequest, "root case requires node_type epic or task")
			return
		}
		exists, err := rootExists(ctx, s.db, req.RootSlug)
		if err != nil {
			slog.Error("check root existence", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
		if exists {
			writeError(w, http.StatusConflict, "slug %q is already registered", req.RootSlug)
			return
		}
		slug = req.RootSlug
	} else {
		// Descendant case.
		if req.NodeType == "epic" {
			writeError(w, http.StatusBadRequest, "epics cannot be descendants")
			return
		}
		exists, err := rootExists(ctx, s.db, req.RootSlug)
		if err != nil {
			slog.Error("check root existence", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
		if !exists {
			writeError(w, http.StatusBadRequest, "root %q has not been registered", req.RootSlug)
			return
		}
		generated, err := generateDescendantSlug(ctx, s.db, req.RootSlug, *req.ParentPath, req.NodeType)
		if err != nil {
			slog.Error("generate descendant slug", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
		slug = generated
	}

	wid := uuid.NewString()
	eid := uuid.NewString()
	now := time.Now().UTC()

	parentPath := ""
	if req.ParentPath != nil {
		parentPath = *req.ParentPath
	}
	payload, err := json.Marshal(map[string]string{
		"root_slug":   req.RootSlug,
		"parent_path": parentPath,
		"node_type":   req.NodeType,
		"actor":       req.Actor,
		"slug":        slug,
	})
	if err != nil {
		slog.Error("marshal register payload", "err", err)
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}

	if err := insertRegister(ctx, s.db, eid, wid, slug, req.Actor, payload, req.Metadata, now); err != nil {
		slog.Error("insert register", "err", err)
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}

	writeJSON(w, http.StatusCreated, RegisterResponse{ID: wid, Slug: slug})
}

// recordEvent handles POST /work-instances/{id}/events.
//
// Two event shapes:
//   - State empty → heartbeat: appends event, bumps last_updated_at.
//   - State "completed" or "abandoned" → state transition: appends
//     event, updates state and terminal_at.
func (s *Server) recordEvent(w http.ResponseWriter, r *http.Request) {
	wid := chi.URLParam(r, "id")
	if wid == "" {
		writeError(w, http.StatusBadRequest, "work-instance id is required")
		return
	}

	var req EventRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON: %v", err)
		return
	}

	ctx := r.Context()

	exists, err := workInstanceExists(ctx, s.db, wid)
	if err != nil {
		slog.Error("check work-instance existence", "err", err)
		writeError(w, http.StatusInternalServerError, "internal error")
		return
	}
	if !exists {
		writeError(w, http.StatusNotFound, "work-instance %q not found", wid)
		return
	}

	eid := uuid.NewString()
	now := time.Now().UTC()

	switch req.State {
	case "":
		if err := insertHeartbeat(ctx, s.db, eid, wid, req.Metadata, now); err != nil {
			slog.Error("insert heartbeat", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
	case string(models.StateCompleted), string(models.StateAbandoned):
		payload, err := json.Marshal(map[string]string{"state": req.State})
		if err != nil {
			slog.Error("marshal state payload", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
		if err := insertStateTransition(ctx, s.db, eid, wid, req.State, payload, req.Metadata, now); err != nil {
			slog.Error("insert state transition", "err", err)
			writeError(w, http.StatusInternalServerError, "internal error")
			return
		}
	default:
		writeError(w, http.StatusBadRequest, "state must be empty (heartbeat), %q, or %q", models.StateCompleted, models.StateAbandoned)
		return
	}

	writeJSON(w, http.StatusCreated, EventResponse{ID: eid})
}

// insertRegister inserts the register event and the initial
// work_instance row in a single transaction.
func insertRegister(ctx context.Context, db *sql.DB, eid, wid, slug, actor string, payload, metadata json.RawMessage, now time.Time) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		eid, wid, models.EventRegister, payload, nullableJSON(metadata), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`INSERT INTO work_instances (id, slug, actor, state, created_at, last_updated_at, terminal_at)
		 VALUES (?, ?, ?, ?, ?, ?, NULL)`,
		wid, slug, actor, models.StateActive, now.UnixNano(), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert work_instance: %w", err)
	}

	return tx.Commit()
}

// insertHeartbeat appends a heartbeat event and bumps the
// work_instance's last_updated_at.
func insertHeartbeat(ctx context.Context, db *sql.DB, eid, wid string, metadata json.RawMessage, now time.Time) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, NULL, ?, ?)`,
		eid, wid, models.EventHeartbeat, nullableJSON(metadata), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`UPDATE work_instances SET last_updated_at = ? WHERE id = ?`,
		now.UnixNano(), wid,
	)
	if err != nil {
		return fmt.Errorf("update work_instance: %w", err)
	}

	return tx.Commit()
}

// insertStateTransition appends a state-transition event and
// updates the work_instance's state, last_updated_at, and
// terminal_at.
func insertStateTransition(ctx context.Context, db *sql.DB, eid, wid, state string, payload, metadata json.RawMessage, now time.Time) error {
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.ExecContext(ctx,
		`INSERT INTO events (id, work_instance_id, type, payload, metadata, received_at)
		 VALUES (?, ?, ?, ?, ?, ?)`,
		eid, wid, models.EventStateTransition, payload, nullableJSON(metadata), now.UnixNano(),
	)
	if err != nil {
		return fmt.Errorf("insert event: %w", err)
	}

	_, err = tx.ExecContext(ctx,
		`UPDATE work_instances SET state = ?, last_updated_at = ?, terminal_at = ? WHERE id = ?`,
		state, now.UnixNano(), now.UnixNano(), wid,
	)
	if err != nil {
		return fmt.Errorf("update work_instance: %w", err)
	}

	return tx.Commit()
}

// workInstanceExists reports whether a work-instance with the
// given ID is present.
func workInstanceExists(ctx context.Context, db *sql.DB, id string) (bool, error) {
	var exists bool
	err := db.QueryRowContext(ctx,
		`SELECT EXISTS(SELECT 1 FROM work_instances WHERE id = ?)`,
		id,
	).Scan(&exists)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return false, err
	}
	return exists, nil
}

// nullableJSON returns nil if the raw message is empty, otherwise
// the raw message itself. Lets sql.Exec write NULL when the
// caller passed no metadata.
func nullableJSON(raw json.RawMessage) any {
	if len(raw) == 0 {
		return nil
	}
	return []byte(raw)
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, status int, format string, args ...any) {
	writeJSON(w, status, map[string]string{"error": fmt.Sprintf(format, args...)})
}
