#!/usr/bin/env bash
#
# assemble.sh — vendor selected shared-agent-rules modules into a
# consuming repo.
#
# Usage:
#   scripts/assemble.sh [manifest-path]
#
# Defaults to docs/agents/shared.manifest.yaml relative to the
# consuming repo's root.
#
# Reads:
#   shared_agent_rules.source     — e.g., github.com/<org>/shared-agent-rules
#   shared_agent_rules.version    — CalVer tag (e.g., 2026-05-15)
#   modules:                       — list of <category>/<name> paths
#   overlay_root:                  — repo-local overlay root
#   spec_root_relpath:             — relative path from each vendored
#                                    shared file to the consumer's vendored
#                                    workstream-tracker/spec/ root. Used to
#                                    substitute `{spec_root}` placeholders
#                                    in cross-references. Defaults to
#                                    ../../../spec (assumes spec/ vendored
#                                    to docs/spec/).
#
# Writes:
#   docs/agents/shared/<module-path>.md per module, each prefixed
#   with a generated-file header naming the source version and
#   suffixed (if a matching overlay exists) with the overlay
#   content below a `## Local additions` delimiter. Cross-references
#   to workstream-tracker/spec/ (written as `{spec_root}/...` in
#   the source modules) are substituted with the configured relpath.
#
# Note on the manifest's `workstream_tracker_spec:` block:
# That block is documentation-only metadata recording the pinned
# spec/ version for downstream audit. This script does NOT clone
# or vendor spec/; consumers vendor workstream-tracker/spec/
# separately. The script does substitute `{spec_root}` placeholders
# in vendored shared content with the configured relpath, so the
# cross-references resolve correctly under the consumer's layout.

set -euo pipefail

MANIFEST="${1:-docs/agents/shared.manifest.yaml}"

if [[ ! -f "$MANIFEST" ]]; then
  echo "assemble.sh: manifest not found at $MANIFEST" >&2
  exit 2
fi

# Tiny YAML reader: this script handles only the shapes the
# example manifest uses. yq is preferred when available; fall
# back to grep/sed for environments without it.
read_field() {
  local field="$1"
  if command -v yq >/dev/null 2>&1; then
    yq -r ".${field} // \"\"" "$MANIFEST"
  else
    # Best-effort grep fallback for `key: value` at top level.
    grep -E "^[[:space:]]*${field##*.}:" "$MANIFEST" \
      | head -n1 | sed -E 's/^[^:]+:[[:space:]]*//; s/[[:space:]]*#.*$//' \
      | tr -d '"'
  fi
}

SOURCE=$(read_field 'shared_agent_rules.source')
VERSION=$(read_field 'shared_agent_rules.version')
OVERLAY_ROOT=$(read_field 'overlay_root')
OVERLAY_ROOT="${OVERLAY_ROOT:-docs/agents/local/overlays/}"
SPEC_ROOT_RELPATH=$(read_field 'spec_root_relpath')
SPEC_ROOT_RELPATH="${SPEC_ROOT_RELPATH:-../../../spec}"

if [[ -z "$SOURCE" || -z "$VERSION" ]]; then
  echo "assemble.sh: manifest missing shared_agent_rules.source or .version" >&2
  exit 2
fi

# Module list: lines under `modules:` starting with `- `.
MODULES=$(awk '
  /^modules:/ { in_modules=1; next }
  /^[a-zA-Z_]+:/ { in_modules=0 }
  in_modules && /^[[:space:]]*-[[:space:]]+/ {
    sub(/^[[:space:]]*-[[:space:]]+/, "");
    sub(/[[:space:]]*#.*$/, "");
    if (length($0) > 0) print
  }
' "$MANIFEST")

# Clone or fetch the shared repo at the named version.
WORKTREE="${TMPDIR:-/tmp}/shared-agent-rules-${VERSION}"
if [[ ! -d "$WORKTREE" ]]; then
  git clone "https://${SOURCE}.git" "$WORKTREE"
fi
git -C "$WORKTREE" fetch --tags >/dev/null 2>&1 || true
git -C "$WORKTREE" checkout --quiet "$VERSION"

SHARED_OUT="docs/agents/shared"
mkdir -p "$SHARED_OUT"

for module in $MODULES; do
  src="$WORKTREE/library/${module}.md"
  dst="$SHARED_OUT/${module}.md"
  if [[ ! -f "$src" ]]; then
    echo "assemble.sh: WARN module not found in upstream: $module" >&2
    continue
  fi
  mkdir -p "$(dirname "$dst")"

  {
    echo "<!--"
    echo "  Generated from shared-agent-rules v${VERSION}."
    echo "  Source module: library/${module}.md"
    echo "  Do not edit this file directly — edit the upstream module"
    echo "  or the matching local overlay (see ${OVERLAY_ROOT}${module}.md)."
    echo "-->"
    echo
    sed "s|{spec_root}|${SPEC_ROOT_RELPATH}|g" "$src"
  } > "$dst"

  overlay="${OVERLAY_ROOT%/}/${module}.md"
  if [[ -f "$overlay" ]]; then
    {
      echo
      echo "## Local additions"
      echo
      sed "s|{spec_root}|${SPEC_ROOT_RELPATH}|g" "$overlay"
    } >> "$dst"
  fi

  echo "wrote $dst"
done

echo "done. shared-agent-rules v${VERSION} vendored into ${SHARED_OUT}/"
